enum Events {
    ADD_BASIC_DETAILS = "ADD_BASIC_DETAILS_TO_HOTEL_CREATION",
    SUBMIT_ID = "SUBMIT_ID",
    ADD_LOCATION_DETAILS = "ADD_BASIC_DETAILS_TO_LOCATION_CREATION",
    ADD_HOTEL_ROOMS = "ADD_HOTEL_ROOMS",
    ADD_HOTEL_ROOMS_PRICE = "ADD_HOTEL_ROOMS_PRICE",
    SUBMITED_ROOM_ID = "SUBMITED_ROOM_ID",
}
export default Events;