enum Events {
	GET_ALL_HOTEL = "GET_ALL_HOTEL",
	GET_ALL_HOTEL_FULFILLED = "GET_ALL_HOTEL_FULFILLED",
	GET_ALL_HOTEL_REJECTED = "GET_ALL_HOTEL_REJECTED",
	CLEAR_GET_ALL_HOTEL = "CLEAR_GET_ALL_HOTEL",
}
export default Events;